[tool.poetry]
name = "braz"
version = "0.1.0"
description = ""
authors = ["dev-macb <dev.macb@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
